import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import fixture from '../testing/survey-candidate.json'
import { parseLocalDraft } from '../modules/map/authoring/files'
import { HttpSurveyCandidateClient, surveyCandidateDraft, type SurveyCandidateReference } from './survey-client'
import { PlatformHttp, type PlatformFetch } from './http'

// Generated by relay.tests.test_survey_candidate_api.completed_candidate and
// SurveyCandidateRegistry.preview from isolated canonical observations/real PNG.
const reference: SurveyCandidateReference = {
  candidateId: fixture.candidate_id, session: fixture.session, intentId: fixture.intent_id,
  runId: fixture.run_id, deviceId: fixture.device_id, connectionEpoch: fixture.connection_epoch, areaId: fixture.area_id,
}
class DecodedPng {
  naturalWidth = fixture.occupancy.grid.width
  naturalHeight = fixture.occupancy.grid.height
  onload: (() => void) | null = null
  onerror: (() => void) | null = null
  set src(value: string) { if (value) queueMicrotask(() => this.onload?.()) }
}
beforeEach(() => vi.stubGlobal('Image', DecodedPng))
afterEach(() => vi.unstubAllGlobals())
const response = (value: unknown) => new Response(JSON.stringify(value), { headers: { 'Content-Type': 'application/json' } })
function client(fetcher: PlatformFetch) {
  return new HttpSurveyCandidateClient(new PlatformHttp({ baseUrl: 'wss://relay.test', sessionId: reference.session, token: 'isolated-token' }, fetcher))
}

describe('Python-generated survey candidate HTTP contract', () => {
  it('loads the real recorded PNG, binds authenticated receipt identity and exports a local unapproved draft', async () => {
    const fetcher = vi.fn<PlatformFetch>().mockResolvedValue(response(fixture))
    const candidate = await client(fetcher).load(reference)
    expect(candidate.image).toMatchObject({ width: 22, height: 2, bytes: 77, sha256: fixture.image.sha256 })
    expect(fetcher.mock.calls[0][0]).toBe(`https://relay.test/api/sessions/${reference.session}/survey-candidates/${reference.candidateId}`)
    expect(fetcher.mock.calls[0][1]).toMatchObject({ method: 'GET', headers: { Authorization: 'Bearer isolated-token' }, cache: 'no-store', credentials: 'omit', redirect: 'error' })
    const draft = parseLocalDraft(JSON.stringify(surveyCandidateDraft(candidate)))
    expect(draft.metadata).toMatchObject({ frame: 'odom', floorId: '', resolutionM: 0.05, originXM: -0.05, originYM: -0.05 })
    expect(draft.metadata.registration).toBeUndefined()
    expect(draft.features).toEqual([]); expect(draft.tags).toEqual([])
    expect(draft.image?.sha256).toBe(fixture.image.sha256)
    expect(candidate.evidence).toEqual(fixture)
  })
  it.each(['session', 'intent_id', 'run_id', 'candidate_id', 'device_id', 'connection_epoch', 'area_id'] as const)('refuses an otherwise valid candidate with changed %s', async (key) => {
    await expect(client(async () => response({ ...fixture, [key]: 'changed' })).load(reference)).rejects.toThrow('incompatible')
  })
  it.each(['input', 'frame', 'registered', 'pose', 'mount', 'image-hash', 'inventory', 'dimensions', 'world', 'bytes', 'metadata'] as const)('refuses damaged %s evidence', async (damage) => {
    const raw = structuredClone(fixture)
    if (damage === 'input') raw.occupancy.input.source.source_id = 'changed'
    if (damage === 'frame') raw.occupancy.grid.frame = 'other'
    if (damage === 'registered') raw.occupancy.grid.registered_to_world = true
    if (damage === 'pose') raw.pose_identity.connection_epoch += 1
    if (damage === 'mount') raw.occupancy.mount_id = 'other'
    if (damage === 'image-hash') raw.image.sha256 = 'a'.repeat(64)
    if (damage === 'inventory') raw.files['occupancy/occupancy.png'].bytes += 1
    if (damage === 'dimensions') raw.occupancy.grid.width += 1
    if (damage === 'world') raw.source.odom_frame = 'world'
    if (damage === 'bytes') raw.image.data_base64 = raw.image.data_base64.replace('Ggo', 'Ggp')
    if (damage === 'metadata') raw.pose_identity.event_id = 'a'.repeat(65 * 1024)
    await expect(client(async () => response(raw)).load(reference)).rejects.toThrow('incompatible')
  })
  it('rejects paths or sessions before fetch and snapshots the caller reference during fetch', async () => {
    const fetcher = vi.fn<PlatformFetch>().mockResolvedValue(response(fixture))
    await expect(client(fetcher).load({ ...reference, candidateId: '../outside' })).rejects.toThrow()
    await expect(client(fetcher).load({ ...reference, session: 'other' })).rejects.toThrow()
    expect(fetcher).not.toHaveBeenCalled()
    const mutable = { ...reference }
    const pending = client(fetcher).load(mutable)
    mutable.runId = 'changed'
    expect((await pending).reference.runId).toBe(reference.runId)
  })
  it('requires an actual decodable PNG and respects cancellation after response', async () => {
    class FailedPng extends DecodedPng { override set src(value: string) { if (value) queueMicrotask(() => this.onerror?.()) } }
    vi.stubGlobal('Image', FailedPng)
    await expect(client(async () => response(fixture)).load(reference)).rejects.toThrow('could not be decoded')
    const controller = new AbortController()
    const fetcher: PlatformFetch = async () => { controller.abort(); return response(fixture) }
    await expect(client(fetcher).load(reference, controller.signal)).rejects.toMatchObject({ name: 'AbortError' })
  })
  it('enforces the candidate response limit and refuses editable drafts over the editor limit', async () => {
    const oversized = new Response('{}', { headers: { 'Content-Length': String(24 * 1024 * 1024 + 1) } })
    await expect(client(async () => oversized).load(reference)).rejects.toThrow('size limit')
    const candidate = await client(async () => response(fixture)).load(reference)
    expect(() => surveyCandidateDraft({ ...candidate, image: { ...candidate.image, bytes: 8 * 1024 * 1024 + 1 } })).toThrow('8 MiB')
  })
})
