import { useState, type ChangeEvent } from 'react'
import {
  JOB_SENTENCE,
  MANUAL_PHOTOS_REQUIRED,
  ROOM_CAPTURE_LABEL,
  bundleImages,
  bundleLabel,
  bundleOptions,
  canRetryJob,
  deriveCatalogLink,
  filesLabel,
  jobTone,
  roomCaptureTone,
  sameBundle,
  submitBlockedReason,
  type CatalogLink,
} from '../../catalog/derive'
import type {
  Building,
  BundleRef,
  CaptureRecord,
  GenerationJob,
  RoomRecord,
} from '../../catalog/types'
import { Pane, type PaneTab } from '../../shell/Pane'
import { formatTime } from '../../shell/format'
import { countWord, noteFromError, type CatalogNoteState } from '../catalog-notes'
import { CatalogNote, LinkNotice } from '../catalog-shared'
import { EmptyModule } from '../shared'
import type { ModuleProps } from '../types'

type WorldsPane = 'rooms' | 'jobs'

const PANES: PaneTab[] = [
  { id: 'rooms', label: 'Rooms' },
  { id: 'jobs', label: 'Jobs' },
]

/**
 * World Builder: rooms with doorway adjacency and a bundle selector, and the
 * generation jobs with their provenance. Submissions and retries go through
 * the catalog client; every one carries public false.
 */
export function WorldsModule({ controller, catalog }: ModuleProps) {
  const [pane, setPane] = useState<WorldsPane>('rooms')
  const [note, setNote] = useState<CatalogNoteState | null>(null)
  const [chosen, setChosen] = useState<Record<string, BundleRef>>({})
  const [openRoom, setOpenRoom] = useState<string | null>(null)
  const { snapshot, client } = catalog
  const link = deriveCatalogLink(
    controller.state,
    'World Builder',
    'submissions and retries are refused',
  )
  const captures = snapshot.captures ?? []
  const photosFor = (roomId: string): number =>
    snapshot.building?.rooms.find((room) => room.room_id === roomId)?.manual_photos ?? 0

  const submit = async (room: RoomRecord, bundle: BundleRef) => {
    try {
      await client.submitGeneration(room.room_id, bundle)
      setNote({
        text: `Submitted ${room.room_id} with ${bundleLabel(bundle, room.manual_photos)} and public false. Uploading now; you can keep working on the next room.`,
        tone: 'muted',
      })
    } catch (error) {
      setNote(noteFromError(error))
    }
  }

  const retry = async (job: GenerationJob) => {
    try {
      await client.retryGeneration(job.room_id)
      const label = job.bundle ? bundleLabel(job.bundle, photosFor(job.room_id)) : 'unreported'
      setNote({
        text: `Retrying ${job.room_id} with the same bundle ${label} and public false. Uploading now.`,
        tone: 'muted',
      })
    } catch (error) {
      setNote(noteFromError(error))
    }
  }

  const addPhotos = async (room: RoomRecord, count: number) => {
    if (count === 0) return
    try {
      await client.addManualPhotos(room.room_id, count)
      setNote({
        text: `Added ${count} ${count === 1 ? 'phone photo' : 'phone photos'} to ${room.room_id}. They are used only when the drone path is unavailable.`,
        tone: 'muted',
      })
    } catch (error) {
      setNote(noteFromError(error))
    }
  }

  const open = (job: GenerationJob) => {
    setOpenRoom(job.room_id)
    setNote({
      text: `Opened ${job.world_id ?? 'the world'} for ${job.room_id}, generated by ${job.model}. Labelled generated; its source photos stay beside it. It is not a factual or safety record.`,
      tone: 'ink',
    })
  }

  return (
    <Pane
      title="World Builder"
      note="Rooms, bundles, and generation jobs. A generated world is never a safety record."
      tabs={PANES}
      activeTab={pane}
      onTabChange={(id) => setPane(id as WorldsPane)}
      tabsLabel="World Builder panes"
    >
      <LinkNotice link={link} label="World Builder connection" />
      <CatalogNote label="World Builder notice" note={note} />
      <div data-two="1">
        {pane === 'rooms' &&
          (snapshot.building === null ? (
            <EmptyModule what="rooms, bundles, or generation jobs" />
          ) : (
            <RoomsPane
              building={snapshot.building}
              captures={captures}
              jobs={snapshot.jobs ?? []}
              chosen={chosen}
              link={link}
              onChoose={(roomId, bundle) => setChosen((prev) => ({ ...prev, [roomId]: bundle }))}
              onSubmit={submit}
              onAddPhotos={addPhotos}
            />
          ))}
        {pane === 'jobs' &&
          (snapshot.jobs === null ? (
            <EmptyModule what="generation jobs" />
          ) : (
            <JobsPane
              jobs={snapshot.jobs}
              captures={captures}
              photosFor={photosFor}
              openRoom={openRoom}
              link={link}
              onRetry={retry}
              onOpen={open}
            />
          ))}
      </div>
    </Pane>
  )
}

function RoomsPane({
  building,
  captures,
  jobs,
  chosen,
  link,
  onChoose,
  onSubmit,
  onAddPhotos,
}: {
  building: Building
  captures: CaptureRecord[]
  jobs: GenerationJob[]
  chosen: Record<string, BundleRef>
  link: CatalogLink
  onChoose: (roomId: string, bundle: BundleRef) => void
  onSubmit: (room: RoomRecord, bundle: BundleRef) => void
  onAddPhotos: (room: RoomRecord, count: number) => void
}) {
  return (
    <section className="cat-swap" aria-label="Rooms">
      <p className="cat-eyebrow">Building — {building.label}</p>
      <p className="wld-intro">
        {countWord(building.rooms.length, 'room')} with explicit doorway adjacency.{' '}
        {building.floor_plan === null ? (
          'No floor-plan reference is recorded; one would be a reference only, never a generation input.'
        ) : (
          <>
            Floor-plan reference <span className="mono">{building.floor_plan}</span> is a reference
            only, never a generation input.
          </>
        )}
      </p>
      {building.rooms.length === 0 ? (
        <p className="cat-empty">
          No rooms are catalogued for this building. A room appears once a capture names it.
        </p>
      ) : (
        building.rooms.map((room) => (
          <RoomCard
            key={room.room_id}
            room={room}
            options={bundleOptions(captures, room.room_id)}
            selected={chosen[room.room_id] ?? null}
            job={jobs.find((job) => job.room_id === room.room_id)}
            link={link}
            onChoose={(bundle) => onChoose(room.room_id, bundle)}
            onSubmit={(bundle) => onSubmit(room, bundle)}
            onAddPhotos={(count) => onAddPhotos(room, count)}
          />
        ))
      )}
    </section>
  )
}

function RoomCard({
  room,
  options,
  selected,
  job,
  link,
  onChoose,
  onSubmit,
  onAddPhotos,
}: {
  room: RoomRecord
  options: BundleRef[]
  selected: BundleRef | null
  job: GenerationJob | undefined
  link: CatalogLink
  onChoose: (bundle: BundleRef) => void
  onSubmit: (bundle: BundleRef) => void
  onAddPhotos: (count: number) => void
}) {
  const bundle =
    selected ??
    options.find((option) => sameBundle(option, room.accepted_bundle)) ??
    options[options.length - 1]
  const images = bundleImages(bundle, room.manual_photos)
  const blocked = submitBlockedReason(link, bundle, room.manual_photos, job)
  const onFiles = (event: ChangeEvent<HTMLInputElement>) => {
    onAddPhotos(event.target.files?.length ?? 0)
    event.target.value = ''
  }
  return (
    <article className="wld-room" aria-label={`Room ${room.room_id}`}>
      <div className="wld-head">
        <span className="wld-name">{room.room_id}</span>
        <span className={`wld-capture tone-${roomCaptureTone(room.capture_status)}`}>
          {ROOM_CAPTURE_LABEL[room.capture_status]}
        </span>
      </div>
      <p className="wld-doorways">
        Doorways to{' '}
        <span className="mono">{room.doorways.length ? room.doorways.join(', ') : 'none recorded'}</span>.
        Both sides of each doorway are kept as composition references, separate from generation
        inputs.
      </p>
      <p className="wld-bundle">
        Accepted bundle{' '}
        <span className="mono">
          {room.accepted_bundle
            ? bundleLabel(room.accepted_bundle, room.manual_photos)
            : 'none accepted yet'}
        </span>
      </p>
      <div className="wld-bundle-options" role="radiogroup" aria-label={`Bundle for ${room.room_id}`}>
        {options.map((option) => {
          const checked = sameBundle(option, bundle)
          return (
            <button
              key={`${option.kind}:${option.capture_id ?? 'manual'}`}
              type="button"
              role="radio"
              aria-checked={checked}
              className={checked ? 'cat-filter is-active' : 'cat-filter'}
              onClick={() => onChoose(option)}
            >
              {bundleLabel(option, room.manual_photos)}
            </button>
          )
        })}
      </div>
      {bundle.kind === 'manual_phone' && (
        <div className="wld-manual">
          <p>
            Manual fallback — exactly {MANUAL_PHOTOS_REQUIRED === 3 ? 'three' : MANUAL_PHOTOS_REQUIRED}{' '}
            overlapping phone photos, added on this page, used when the drone path is unavailable.
          </p>
          <label className="wld-manual-add">
            Add phone photos
            <input type="file" accept="image/*" multiple disabled={!link.up} onChange={onFiles} />
          </label>
        </div>
      )}
      <p className="wld-plan">
        Upload set {images} {images === 1 ? 'image' : 'images'}, model {room.model}
      </p>
      {blocked && <p className="wld-block">{blocked}</p>}
      <div className="wld-actions">
        <button
          type="button"
          className="cat-button is-primary is-submit"
          disabled={blocked !== null}
          title={blocked ?? undefined}
          onClick={() => onSubmit(bundle)}
        >
          Submit for generation
        </button>
        <span className="wld-public">public: false</span>
      </div>
    </article>
  )
}

function JobsPane({
  jobs,
  captures,
  photosFor,
  openRoom,
  link,
  onRetry,
  onOpen,
}: {
  jobs: GenerationJob[]
  captures: CaptureRecord[]
  photosFor: (roomId: string) => number
  openRoom: string | null
  link: CatalogLink
  onRetry: (job: GenerationJob) => void
  onOpen: (job: GenerationJob) => void
}) {
  return (
    <section className="cat-swap" aria-label="Generation jobs">
      <p className="cat-eyebrow">Generation jobs</p>
      {jobs.length === 0 ? (
        <p className="cat-empty">
          No generation jobs exist for this session. Submit a room to start one.
        </p>
      ) : (
        jobs.map((job) => (
          <JobCard
            key={job.room_id}
            job={job}
            captures={captures}
            photos={photosFor(job.room_id)}
            open={openRoom === job.room_id}
            link={link}
            onRetry={() => onRetry(job)}
            onOpen={() => onOpen(job)}
          />
        ))
      )}
      <p className="wld-footnote">
        A generated world is labelled generated. Its source photos stay visible beside it. It is
        not a factual or safety record.
      </p>
    </section>
  )
}

function JobCard({
  job,
  captures,
  photos,
  open,
  link,
  onRetry,
  onOpen,
}: {
  job: GenerationJob
  captures: CaptureRecord[]
  photos: number
  open: boolean
  link: CatalogLink
  onRetry: () => void
  onOpen: () => void
}) {
  const blocked = link.up ? undefined : `The console connection is ${link.status}. Nothing can be sent.`
  return (
    <article className="wld-job" aria-label={`Job ${job.room_id}`}>
      <div className="wld-head">
        <span className="wld-job-room">{job.room_id}</span>
        <span className={`wld-job-state tone-${jobTone(job.state)}`}>{job.state}</span>
        <span className="wld-job-time">{formatTime(job.updated_at)}</span>
      </div>
      <p className="wld-job-sentence">{JOB_SENTENCE[job.state]}</p>
      <p className="wld-job-meta">
        op {job.operation_id ?? '—'} · world {job.world_id ?? '—'} · model {job.model} · {job.assets}{' '}
        · source {job.bundle ? bundleLabel(job.bundle, photos) : 'none'}
      </p>
      <div className="wld-job-actions">
        {canRetryJob(job) && (
          <button
            type="button"
            className="cat-button is-job"
            disabled={!link.up}
            title={blocked}
            onClick={onRetry}
          >
            Retry with the same capture
          </button>
        )}
        {job.state === 'succeeded' && (
          <button
            type="button"
            className="cat-button is-primary is-job"
            aria-pressed={open}
            onClick={onOpen}
          >
            Open room world
          </button>
        )}
        <span className="wld-public">public: {String(job.public)}</span>
      </div>
      {open && <OpenWorld job={job} captures={captures} photos={photos} />}
    </article>
  )
}

/** The generated world, labelled as such, with its sources listed beside it. */
function OpenWorld({
  job,
  captures,
  photos,
}: {
  job: GenerationJob
  captures: CaptureRecord[]
  photos: number
}) {
  return (
    <section className="wld-open" aria-label={`Open world ${job.world_id ?? job.room_id}`}>
      <div className="wld-open-head">
        <span className="wld-open-id">{job.world_id ?? 'world id unreported'}</span>
        <span className="wld-generated">generated</span>
        <span className="wld-open-model">
          by {job.model} for {job.room_id}
        </span>
      </div>
      <p>Labelled generated. Its source photos stay beside it. It is not a factual or safety record.</p>
      <p className="cat-eyebrow">Sources</p>
      <ul className="wld-sources">
        <li>{sourceLine(job, captures, photos)}</li>
      </ul>
    </section>
  )
}

function sourceLine(job: GenerationJob, captures: CaptureRecord[], photos: number): string {
  if (job.bundle === null) return 'no bundle recorded'
  if (job.bundle.kind === 'manual_phone') return `manual phone fallback · ${photos} phone photos`
  const capture = captures.find((item) => item.capture_id === job.bundle?.capture_id)
  if (!capture) return `${job.bundle.capture_id ?? 'capture unreported'} · ${job.bundle.kind} · files unreported`
  return `${capture.capture_id} · ${capture.pattern} · ${filesLabel(capture.files)} · ${capture.checksum ?? 'checksum unreported'}`
}
