package org.worldofhacks.sweep.bridge.core

import org.worldofhacks.sweep.bridge.core.json.Json
import org.worldofhacks.sweep.bridge.core.json.JsonArray
import org.worldofhacks.sweep.bridge.core.json.JsonObject
import org.worldofhacks.sweep.bridge.core.json.JsonString
import org.worldofhacks.sweep.bridge.core.json.JsonValue

/**
 * Test vectors generated by `adapters/dji_mini3/vectors.py` (run `uv run python -m
 * adapters.dji_mini3.vectors` from the repo root) so the Kotlin encoders byte-match
 * the Python relay. `adapters/dji_mini3/test_vectors.py` fails if the files drift.
 */
object Fixtures {
    fun load(name: String): JsonObject {
        val stream = checkNotNull(Fixtures::class.java.getResourceAsStream("/vectors/$name")) {
            "missing fixture /vectors/$name"
        }
        val text = stream.use { it.readBytes().toString(Charsets.UTF_8) }
        return Json.parse(text) as JsonObject
    }

    fun cases(name: String): List<JsonObject> =
        (load(name)["cases"] as JsonArray).items.map { it as JsonObject }

    fun JsonObject.string(key: String): String = (this[key] as JsonString).value

    fun JsonObject.obj(key: String): JsonObject = this[key] as JsonObject

    fun JsonObject.any(key: String): JsonValue = checkNotNull(this[key]) { "missing $key" }
}
